import { randomUUID } from "node:crypto"
import { createSupabaseAdminClient } from "@/lib/supabase/server"
import type {
  EmailTemplate,
  EmailTemplateCreatePayload,
  EmailTemplateUpdatePayload,
  ToneConversionPayload,
  ToneConversionStatus,
  ToneConversionTarget,
  TemplateFieldMapping,
  TemplateVariantBundle,
  TemplateVariantItem,
} from "@/lib/email-templates/types"

type AuthContext = {
  userId: string
  isAdmin: boolean
}

type EmailTemplateRow = {
  id: string
  name: string
  owner_id: string
  owner_role: "admin" | "user"
  source_type: "html" | "text" | "eml"
  original_file_name: string | null
  subject: string | null
  raw_content: string
  html_content: string
  text_content: string
  conversion_status: "none" | "pending_review" | "approved" | "rejected"
  conversion_target_tone: "tegezo" | null
  converted_subject: string | null
  converted_html_content: string | null
  converted_text_content: string | null
  conversion_notes: string | null
  mappings: unknown
  created_at: string
  updated_at: string
}

type TemplateVariantBundleRow = {
  template_id: string
  owner_id: string
  owner_role: "admin" | "user"
  variants: unknown
  updated_at: string
}

const EMAIL_TEMPLATE_CONVERSION_COLUMNS = [
  "conversion_status",
  "conversion_target_tone",
  "converted_subject",
  "converted_html_content",
  "converted_text_content",
] as const

function isAutogeneratedTemplateName(name: string): boolean {
  return name.trim().startsWith("[AUTO]")
}

function canReadTemplate(template: EmailTemplate, auth: AuthContext): boolean {
  return auth.isAdmin || template.ownerId === auth.userId
}

function canWriteTemplate(template: EmailTemplate, auth: AuthContext): boolean {
  return template.ownerId === auth.userId
}

function isMissingEmailTemplateConversionColumnError(message: string): boolean {
  const normalized = message.toLowerCase()
  if (!normalized.includes("email_templates")) return false
  if (!normalized.includes("column") && !normalized.includes("schema cache")) return false
  return EMAIL_TEMPLATE_CONVERSION_COLUMNS.some((column) => normalized.includes(column))
}

function stripConversionPersistenceFields<T extends Record<string, unknown>>(payload: T): T {
  const next = { ...payload }
  for (const column of EMAIL_TEMPLATE_CONVERSION_COLUMNS) {
    delete next[column]
  }
  return next
}

function mapRowToTemplate(row: EmailTemplateRow): EmailTemplate {
  return {
    id: row.id,
    name: row.name,
    ownerId: row.owner_id,
    ownerRole: row.owner_role,
    sourceType: row.source_type,
    originalFileName: row.original_file_name ?? undefined,
    subject: row.subject ?? undefined,
    rawContent: row.raw_content,
    htmlContent: row.html_content,
    textContent: row.text_content,
    conversionStatus: row.conversion_status ?? "none",
    conversionTargetTone: row.conversion_target_tone ?? undefined,
    convertedSubject: row.converted_subject ?? undefined,
    convertedHtmlContent: row.converted_html_content ?? undefined,
    convertedTextContent: row.converted_text_content ?? undefined,
    conversionNotes: row.conversion_notes ?? undefined,
    mappings: normalizeMappings(row.mappings),
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  }
}

function normalizeVariantItem(input: unknown): TemplateVariantItem | null {
  if (!input || typeof input !== "object") return null
  const item = input as Record<string, unknown>
  const tone = item.tone === "magazo" || item.tone === "tegezo" ? item.tone : null
  const product = item.product === "allianz_eletprogram" || item.product === "allianz_bonusz_eletprogram" ? item.product : null
  const currency = item.currency === "HUF" || item.currency === "EUR" ? item.currency : null
  const goal = item.goal === "tokenoveles" || item.goal === "nyugdij" ? item.goal : null
  if (!tone || !product || !currency || !goal) return null
  const id = String(item.id ?? "").trim()
  const name = String(item.name ?? "").trim()
  const emlFileName = String(item.emlFileName ?? "").trim()
  const htmlFileName = String(item.htmlFileName ?? "").trim()
  const subject = String(item.subject ?? "")
  const htmlContent = String(item.htmlContent ?? "")
  const plainContent = String(item.plainContent ?? "")
  const emlContent = String(item.emlContent ?? "")
  if (!id || !name || !emlFileName || !htmlFileName || !emlContent) return null
  return {
    id,
    name,
    tone,
    product,
    currency,
    goal,
    emlFileName,
    htmlFileName,
    subject,
    htmlContent,
    plainContent,
    emlContent,
  }
}

function normalizeVariantBundle(row: TemplateVariantBundleRow): TemplateVariantBundle | null {
  const variantsRaw = Array.isArray(row.variants) ? row.variants : []
  const variants = variantsRaw.map((entry) => normalizeVariantItem(entry)).filter((entry): entry is TemplateVariantItem => Boolean(entry))
  if (variants.length === 0) return null
  return {
    templateId: row.template_id,
    variants,
    updatedAt: row.updated_at,
  }
}

async function getVariantBundleMapForTemplateIds(auth: AuthContext, templateIds: string[]): Promise<Map<string, TemplateVariantBundle>> {
  const result = new Map<string, TemplateVariantBundle>()
  if (templateIds.length === 0) return result
  const supabase = createSupabaseAdminClient()
  let query = supabase.from("email_template_variant_bundles").select("*").in("template_id", templateIds)
  if (!auth.isAdmin) {
    query = query.eq("owner_id", auth.userId)
  }
  const { data, error } = await query
  if (error) {
    if (/email_template_variant_bundles/i.test(error.message)) return result
    throw new Error(error.message)
  }
  for (const row of data ?? []) {
    const normalized = normalizeVariantBundle(row as TemplateVariantBundleRow)
    if (!normalized) continue
    result.set(normalized.templateId, normalized)
  }
  return result
}

function normalizeMappings(input: unknown): TemplateFieldMapping[] {
  if (!Array.isArray(input)) return []
  const seen = new Set<string>()
  const normalized: TemplateFieldMapping[] = []
  for (const entry of input) {
    if (!entry || typeof entry !== "object") continue
    const candidate = entry as Record<string, unknown>
    const key = String(candidate.key ?? "").trim() as TemplateFieldMapping["key"]
    if (
      key !== "name" &&
      key !== "amount" &&
      key !== "deadline" &&
      key !== "currency" &&
      key !== "tone" &&
      key !== "calculator_table" &&
      key !== "fixed_small_amount" &&
      key !== "fixed_large_amount" &&
      key !== "retirement_section" &&
      key !== "bonus_section"
    )
      continue
    if (seen.has(key)) continue
    const tokenRaw = String(candidate.token ?? "").trim()
    const token = tokenRaw || `{{${key}}}`
    const labelRaw = String(candidate.label ?? "").trim()
    const label =
      labelRaw ||
      (key === "name"
        ? "Név"
        : key === "amount"
          ? "Összeg"
          : key === "deadline"
            ? "Határidő"
            : key === "currency"
              ? "Pénznem"
              : key === "tone"
                ? "Hangnem"
                : key === "calculator_table"
                  ? "Kalkulátor táblázat"
                  : key === "fixed_small_amount"
                    ? "Fix kis összeg"
                    : key === "fixed_large_amount"
                      ? "Fix nagy összeg"
                      : key === "retirement_section"
                        ? "Nyugdíj szekció"
                        : "Bónusz szekció")
    const sourceSnippet = String(candidate.sourceSnippet ?? "").trim() || undefined
    const confidence = Number(candidate.confidence)
    normalized.push({
      key,
      token,
      label,
      sourceSnippet,
      confidence: Number.isFinite(confidence) ? confidence : undefined,
    })
    seen.add(key)
  }
  return normalized
}

function normalizePayload(payload: EmailTemplateCreatePayload | EmailTemplateUpdatePayload) {
  const name = typeof payload.name === "string" ? payload.name.trim() : undefined
  const sourceType =
    payload.sourceType === "html" || payload.sourceType === "text" || payload.sourceType === "eml"
      ? payload.sourceType
      : undefined
  const originalFileName = typeof payload.originalFileName === "string" ? payload.originalFileName.trim() || undefined : undefined
  const subject = typeof payload.subject === "string" ? payload.subject.trim() || undefined : undefined
  const rawContent = typeof payload.rawContent === "string" ? payload.rawContent : undefined
  const htmlContent = typeof payload.htmlContent === "string" ? payload.htmlContent : undefined
  const textContent = typeof payload.textContent === "string" ? payload.textContent : undefined
  const mappings = payload.mappings === undefined ? undefined : normalizeMappings(payload.mappings)
  const conversion = normalizeConversionPayload(payload.conversion)

  return { name, sourceType, originalFileName, subject, rawContent, htmlContent, textContent, mappings, conversion }
}

function normalizeConversionPayload(input: ToneConversionPayload | undefined): ToneConversionPayload | undefined {
  if (!input || typeof input !== "object") return undefined
  const status = normalizeConversionStatus(input.status)
  const targetTone = input.targetTone === "tegezo" ? ("tegezo" as ToneConversionTarget) : undefined
  const convertedSubject = typeof input.convertedSubject === "string" ? input.convertedSubject.trim() || undefined : undefined
  const convertedHtmlContent = typeof input.convertedHtmlContent === "string" ? input.convertedHtmlContent.trim() || undefined : undefined
  const convertedTextContent = typeof input.convertedTextContent === "string" ? input.convertedTextContent.trim() || undefined : undefined
  const notes = typeof input.notes === "string" ? input.notes.trim() || undefined : undefined
  return {
    status,
    targetTone,
    convertedSubject,
    convertedHtmlContent,
    convertedTextContent,
    notes,
  }
}

function normalizeConversionStatus(input: unknown): ToneConversionStatus {
  if (input === "pending_review" || input === "approved" || input === "rejected") return input
  return "none"
}

function ensureConversionPayloadAllowed(payload: ToneConversionPayload | undefined) {
  if (!payload) return
  const hasConvertedValues = Boolean(payload.convertedSubject || payload.convertedHtmlContent || payload.convertedTextContent)
  if (!hasConvertedValues && payload.status !== "approved") return
  if (payload.status !== "approved") {
    throw new Error("A tegező konverzió csak jóváhagyott állapotban menthető.")
  }
  if (payload.targetTone !== "tegezo") {
    throw new Error("A konverziós célhangnem kötelező és csak tegező lehet.")
  }
  if (!payload.convertedHtmlContent && !payload.convertedTextContent) {
    throw new Error("A jóváhagyott konverzióhoz szükséges átalakított tartalom.")
  }
}

export async function listEmailTemplates(auth: AuthContext): Promise<EmailTemplate[]> {
  const supabase = createSupabaseAdminClient()
  let query = supabase.from("email_templates").select("*").order("updated_at", { ascending: false })
  if (!auth.isAdmin) {
    query = query.eq("owner_id", auth.userId)
  }

  const { data, error } = await query
  if (error) throw new Error(error.message)

  const templates = (data ?? [])
    .map((row) => mapRowToTemplate(row as EmailTemplateRow))
    .filter((template) => !isAutogeneratedTemplateName(template.name))
    .filter((template) => canReadTemplate(template, auth))
  const bundleMap = await getVariantBundleMapForTemplateIds(
    auth,
    templates.map((template) => template.id),
  )
  return templates.map((template) => ({
    ...template,
    variantBundle: bundleMap.get(template.id),
  }))
}

export async function getEmailTemplateById(auth: AuthContext, id: string): Promise<EmailTemplate | null> {
  const supabase = createSupabaseAdminClient()
  let query = supabase.from("email_templates").select("*").eq("id", id)
  if (!auth.isAdmin) {
    query = query.eq("owner_id", auth.userId)
  }
  const { data, error } = await query.maybeSingle()
  if (error) throw new Error(error.message)
  if (!data) return null
  const template = mapRowToTemplate(data as EmailTemplateRow)
  if (!canReadTemplate(template, auth)) return null
  const bundleMap = await getVariantBundleMapForTemplateIds(auth, [template.id])
  return {
    ...template,
    variantBundle: bundleMap.get(template.id),
  }
}

export async function createEmailTemplate(auth: AuthContext, payload: EmailTemplateCreatePayload): Promise<EmailTemplate> {
  const normalized = normalizePayload(payload)
  if (!normalized.name) throw new Error("A sablon neve kötelező.")
  if (!normalized.sourceType) throw new Error("A sablon típusa kötelező.")
  if (!normalized.rawContent?.trim()) throw new Error("A sablon tartalma kötelező.")
  if (!normalized.mappings || normalized.mappings.length === 0) throw new Error("Legalább egy dinamikus mezőt jelölj ki.")
  ensureConversionPayloadAllowed(normalized.conversion)
  const conversion = normalized.conversion
  const effectiveSubject = normalized.subject
  const effectiveHtml = normalized.htmlContent ?? (normalized.sourceType === "text" ? "" : normalized.rawContent)
  const effectiveText = normalized.textContent ?? (normalized.sourceType === "html" ? "" : normalized.rawContent)

  const template: EmailTemplate = {
    id: randomUUID(),
    name: normalized.name,
    ownerId: auth.userId,
    ownerRole: auth.isAdmin ? "admin" : "user",
    sourceType: normalized.sourceType,
    originalFileName: normalized.originalFileName,
    subject: effectiveSubject,
    rawContent: normalized.rawContent,
    htmlContent: effectiveHtml,
    textContent: effectiveText,
    conversionStatus: conversion?.status ?? "none",
    conversionTargetTone: conversion?.targetTone,
    convertedSubject: conversion?.convertedSubject,
    convertedHtmlContent: conversion?.convertedHtmlContent,
    convertedTextContent: conversion?.convertedTextContent,
    conversionNotes: conversion?.notes,
    mappings: normalized.mappings,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }

  const supabase = createSupabaseAdminClient()
  const insert = {
    id: template.id,
    name: template.name,
    owner_id: template.ownerId,
    owner_role: template.ownerRole,
    source_type: template.sourceType,
    original_file_name: template.originalFileName ?? null,
    subject: template.subject ?? null,
    raw_content: template.rawContent,
    html_content: template.htmlContent,
    text_content: template.textContent,
    conversion_status: template.conversionStatus,
    conversion_target_tone: template.conversionTargetTone ?? null,
    converted_subject: template.convertedSubject ?? null,
    converted_html_content: template.convertedHtmlContent ?? null,
    converted_text_content: template.convertedTextContent ?? null,
    mappings: template.mappings,
  }

  let { data, error } = await supabase.from("email_templates").insert(insert).select("*").single()
  if ((error || !data) && error?.message && isMissingEmailTemplateConversionColumnError(error.message)) {
    ;({ data, error } = await supabase
      .from("email_templates")
      .insert(stripConversionPersistenceFields(insert))
      .select("*")
      .single())
  }
  if (error || !data) throw new Error(error?.message ?? "Mentési hiba.")
  return mapRowToTemplate(data as EmailTemplateRow)
}

export async function updateEmailTemplate(
  auth: AuthContext,
  id: string,
  payload: EmailTemplateUpdatePayload,
): Promise<EmailTemplate> {
  const supabase = createSupabaseAdminClient()
  const { data: existingRow, error: existingError } = await supabase.from("email_templates").select("*").eq("id", id).maybeSingle()
  if (existingError) throw new Error(existingError.message)
  const existing = existingRow ? mapRowToTemplate(existingRow as EmailTemplateRow) : null
  if (!existing) throw new Error("A sablon nem található.")
  if (!canWriteTemplate(existing, auth)) throw new Error("Nincs jogosultság a sablon módosításához.")

  const normalized = normalizePayload(payload)
  ensureConversionPayloadAllowed(normalized.conversion)

  const updateData = {
    ...(normalized.name !== undefined ? { name: normalized.name } : {}),
    ...(normalized.sourceType !== undefined ? { source_type: normalized.sourceType } : {}),
    ...(normalized.originalFileName !== undefined ? { original_file_name: normalized.originalFileName ?? null } : {}),
    ...(normalized.subject !== undefined ? { subject: normalized.subject ?? null } : {}),
    ...(normalized.rawContent !== undefined ? { raw_content: normalized.rawContent } : {}),
    ...(normalized.htmlContent !== undefined ? { html_content: normalized.htmlContent } : {}),
    ...(normalized.textContent !== undefined ? { text_content: normalized.textContent } : {}),
    ...(normalized.conversion !== undefined ? { conversion_status: normalized.conversion.status } : {}),
    ...(normalized.conversion !== undefined ? { conversion_target_tone: normalized.conversion.targetTone ?? null } : {}),
    ...(normalized.conversion !== undefined ? { converted_subject: normalized.conversion.convertedSubject ?? null } : {}),
    ...(normalized.conversion !== undefined ? { converted_html_content: normalized.conversion.convertedHtmlContent ?? null } : {}),
    ...(normalized.conversion !== undefined ? { converted_text_content: normalized.conversion.convertedTextContent ?? null } : {}),
    ...(normalized.mappings !== undefined ? { mappings: normalized.mappings } : {}),
    updated_at: new Date().toISOString(),
  }

  let { data, error } = await supabase
    .from("email_templates")
    .update(updateData)
    .eq("id", id)
    .eq("owner_id", auth.userId)
    .select("*")
    .single()
  if ((error || !data) && error?.message && isMissingEmailTemplateConversionColumnError(error.message)) {
    ;({ data, error } = await supabase
      .from("email_templates")
      .update(stripConversionPersistenceFields(updateData))
      .eq("id", id)
      .eq("owner_id", auth.userId)
      .select("*")
      .single())
  }
  if (error || !data) throw new Error(error?.message ?? "Mentési hiba.")
  return mapRowToTemplate(data as EmailTemplateRow)
}

export async function deleteEmailTemplate(auth: AuthContext, id: string): Promise<void> {
  const existing = await getEmailTemplateById({ userId: auth.userId, isAdmin: true }, id)
  if (!existing) throw new Error("A sablon nem található.")
  if (!canWriteTemplate(existing, auth)) throw new Error("Nincs jogosultság a sablon törléséhez.")

  const supabase = createSupabaseAdminClient()
  const { error: bundleDeleteError } = await supabase.from("email_template_variant_bundles").delete().eq("template_id", id).eq("owner_id", auth.userId)
  if (bundleDeleteError && !/email_template_variant_bundles/i.test(bundleDeleteError.message)) {
    throw new Error(bundleDeleteError.message)
  }
  const { error } = await supabase.from("email_templates").delete().eq("id", id).eq("owner_id", auth.userId)
  if (error) throw new Error(error.message)
}

export async function upsertTemplateVariantBundle(
  auth: AuthContext,
  templateId: string,
  variants: TemplateVariantItem[],
): Promise<TemplateVariantBundle> {
  const template = await getEmailTemplateById(auth, templateId)
  if (!template) throw new Error("A sablon nem található.")
  if (!canWriteTemplate(template, auth)) throw new Error("Nincs jogosultság a sablon módosításához.")
  const supabase = createSupabaseAdminClient()
  const payload = {
    template_id: templateId,
    owner_id: auth.userId,
    owner_role: auth.isAdmin ? "admin" : "user",
    variants,
    updated_at: new Date().toISOString(),
  }
  const { data, error } = await supabase
    .from("email_template_variant_bundles")
    .upsert(payload, { onConflict: "template_id" })
    .select("*")
    .single()
  if (error || !data) {
    const message = error?.message ?? "Variáns mentési hiba."
    // Graceful compatibility fallback: allow ZIP export even when migration/table is not yet applied.
    if (/email_template_variant_bundles/i.test(message)) {
      return {
        templateId,
        variants,
        updatedAt: payload.updated_at,
      }
    }
    throw new Error(message)
  }
  const normalized = normalizeVariantBundle(data as TemplateVariantBundleRow)
  if (!normalized) throw new Error("A variáns csomag mentése sikertelen.")
  return normalized
}
